# -*- coding: utf-8 -*-
"""day_2_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tS3sAnYWrspMl0SIctpN2SmCN9UNEfVd
"""

!pip install pandas scikit-learn

import pandas as pd
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Load the dataset
kindle_reviews = pd.read_csv('/content/all_kindle_review.csv')

# Select relevant columns
reviews = kindle_reviews[['reviewText', 'rating']]

# Create sentiment labels (1 for positive, 0 for negative)
reviews['Sentiment'] = reviews['rating'].apply(lambda x: 1 if x >= 4 else (0 if x <= 2 else None))

# Drop neutral reviews
reviews = reviews.dropna(subset=['Sentiment'])

# Reset the index
reviews_cleaned = reviews[['reviewText', 'Sentiment']].reset_index(drop=True)

# Text Preprocessing Function
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation
    text = ''.join(char for char in text if char not in string.punctuation)
    # Remove stop words (optional, requires nltk stopwords)
    return text

# Apply preprocessing to review text
reviews_cleaned['reviewText'] = reviews_cleaned['reviewText'].apply(preprocess_text)

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=2500)

# Transform the review text into numerical features
X = tfidf.fit_transform(reviews_cleaned['reviewText']).toarray()
y = reviews_cleaned['Sentiment']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Naive Bayes Classifier
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate the performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

"""# New Section"""